//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookDatabase.API.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract(IsReference = true)]
    public partial class Book
    {
        [DataMember]
        public int BookID { get; set; }
        [DataMember]
        public int AuthorID { get; set; }
        [DataMember]
        public int PublisherID { get; set; }
        [DataMember]
        public int EditionID { get; set; }
        [DataMember]
        public string ISBN { get; set; }
        [DataMember]
        public string Title { get; set; }
        [DataMember]
        public string SubTitle { get; set; }
        [DataMember]
        public System.DateTime Release { get; set; }
        [DataMember]
        public decimal Price { get; set; }
        [DataMember]
        public string UrlPath { get; set; }
        [DataMember]
        public virtual Author Author { get; set; }
        [DataMember]
        public virtual Edition Edition { get; set; }
        [DataMember]
        public virtual Publisher Publisher { get; set; }
    }
}
